# name: Health check

# on:
#   push:
#     branches:
#       - master
#   schedule:
#     - cron: '20/15 * * * *'

# jobs:
#   health-check:
#     runs-on: ubuntu-20.04
#     steps:
#     - name: periodic health check
#       uses: jtalk/url-health-check-action@v1.2
#       with:
#         url: https://glacial-shore-21319.herokuapp.com/health
#         follow-redirect: no
#         max-attempts: 3
#         retry-delay: 20s
